name: Client CI

on:
  push:
    paths:
      - "server"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /var/www/torrent-streaming
            git reset --hard
            git pull
            npm --prefix server install
            npm --prefix server run build
            pm2 reload server
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
