name: Server CI

on:
  push:
    paths:
      - ".github/workflows/server-ci.yml"
      - "server/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            entities:
              - "server/src/entities/**"
            cron:
              - "server/src/cron.ts"
              - "server/src/services/update-movies.ts"
              - "server/src/services/delete-old-torrent-files.ts"

      - name: Build
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /var/www/torrent-streaming
            git reset --hard
            git pull
            npm --prefix server install
            npm --prefix server run build
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}

      - name: Migrate Database
        if: steps.filter.outputs.entities == 'true'
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /var/www/torrent-streaming
            node server/build/cli.js migrate-database
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}

      - name: Reload Server
        if: always()
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            pm2 reload torrent-streaming --time
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}

      - name: Reload Cron
        if: steps.filter.outputs.cron == 'true'
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            pm2 reload torrent-streaming-cron --time
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
