name: Server CI

on:
  push:
    paths:
      - ".github/workflows/server-ci.yml"
      - "server/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            entities:
              - ".github/workflows/server-ci.yml"
              - "server/src/entities/**"
            cron:
              - ".github/workflows/server-ci.yml"
              - "server/src/cron.ts"
              - "server/src/services/update-movies.ts"
              - "server/src/services/delete-old-torrent-files.ts"

      - name: Prepare SSH
        run: |
          install -m 700 -d ~/.ssh
          printf '%s\n' "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          if [ -n "${{ secrets.SSH_KNOWN_HOSTS }}" ]; then
            printf '%s\n' "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          else
            ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
          fi

      - name: Build
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /var/www/torrent-streaming
            git reset --hard
            git pull
            npm --prefix server install
            npm --prefix server run build
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_KEY }}

      - name: Migrate Database
        if: steps.filter.outputs.entities == 'true'
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /var/www/torrent-streaming
            node server/build/cli.js migrate-database
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_KEY }}

      - name: Reload Server
        if: always()
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            pm2 reload torrent-streaming --time
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_KEY }}

      - name: Reload Cron
        if: steps.filter.outputs.cron == 'true'
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            pm2 reload torrent-streaming-cron --time
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_KEY }}
